AWSTemplateFormatVersion: 2010-09-09
Description: Hotels
Resources:
  dbs-s3-mp-travel-hotels:
    Type: AWS::S3::Bucket
    Persist: true
    Configuration:
      Bucket:
        Pipeline::Security:
          - Allow: [list, read, write, delete]
            Source: my-instance
        Properties:
          VersioningConfiguration:
            Status: Enabled
  autocompletedataset:
    Type: AWS::Elasticsearch
    Persist: true
    Configuration:
      Domain:
        Pipeline::Security:
          - Source: my-instance
            Allow: [ read, write, delete ]
        Properties:
          ElasticsearchClusterConfig:
            InstanceCount: 1
            InstanceType: m4.10xlarge.elasticsearch
          ElasticsearchVersion: '6.3'
          SnapshotOptions:
            AutomatedSnapshotStartHour: 00:00 UTC
  Property:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        HashKeyElement:
          AttributeName: property_id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: '500'
        WriteCapacityUnits: '500'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 26cc3bf9-16b5-46fa-b773-679719a4f19a
  SearchAPILambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          Ref: rtmp??
        S3Key:
          Ref: hotels/lambda-hotels-search.zip
      FunctionName: lambda-hotels-search
      Handler: index.handler
      MemorySize: '1024'
      Role:
        'Fn::GetAtt':
          - BackingLambdaExecutionRole
      Runtime: nodejs8.10
      Timeout: '120'
    DependsOn:
      - Property
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2c7c971a-30fc-4e90-876e-a938379acedd
  HotelDetailsAPILambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          Ref: rtmp??
        S3Key:
          Ref: hotels/lambda-hotel-details.zip
      FunctionName: lambda-hotel-details
      Handler: index.handler
      MemorySize: '1024'
      Role:
        'Fn::GetAtt':
          - BackingLambdaExecutionRole
      Runtime: nodejs8.10
      Timeout: '120'
    DependsOn:
      - Property
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 27defe61-6107-4d89-91ac-c2cde38996b2
  AutocompleteDataImportLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          Ref: rtmp??
        S3Key:
          Ref: hotels/lambda-autocomplete-dataimport.zip
      FunctionName: lambda-autocomplete-dataimport
      Handler: index.handler
      MemorySize: '1024'
      Role:
        'Fn::GetAtt':
          - BackingLambdaExecutionRole
      Runtime: nodejs8.10
      Timeout: '600'
    DependsOn:
      - Property
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b27df1b4-5407-4098-a832-facfecb264b8		
AutocompleteLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          Ref: rtmp??
        S3Key:
          Ref: hotels/lambda-autocomplete.zip
      FunctionName: lambda-autocomplete
      Handler: index.handler
      MemorySize: '1024'
      Role:
        'Fn::GetAtt':
          - BackingLambdaExecutionRole
      Runtime: nodejs8.10
      Timeout: '120'
    DependsOn:
      - Property
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b27df1b4-5407-4098-a832-facfecb264b8
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref >-
        SearchAPILambdaFunction, HotelDetailsAPILambdaFunction,
        AutocompleteLambdaFunction
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 437d7b08-2522-4767-93fb-a6d6c2cdd8b0
  BackingLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
            RoleName: rtmp-execution-role
            Path: /
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:UpdateItem'
                  - 'lambda:InvokeFunction'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a36f685d-0d1e-4ab5-8bed-f725454c9994
  RestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: rtmp gateway
      Name: rtmp-uat-gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f88db4e6-a9ed-410a-a368-bb5cc7e2c221
  HotelsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId:
        Ref: RestApi
      ParentId:
        'Fn::GetAtt':
          - RestApi
          - RootResourceId
      PathPart: hotels
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 91b26e8c-4a3c-441a-b1f3-d1a737d5e6c0
  SearchResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestApi
      ParentId:
        'Fn::GetAtt':
          - PropertiesResource
      PathPart: search
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 225600dc-f156-4ea2-bf90-7c6e997947fe
  SearchMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
      HttpMethod: GET
      Integration:
        Credentials:
          'Fn::GetAtt':
            - ExecutionRole
            - Arn
        IntegrationHttpMethod: GET
        CacheKeyParameters:
          - method.request.path.proxy
        RequestParameters:
          integration.request.path.proxy: method.request.path.proxy
        IntegrationResponses:
          - StatusCode: '200'
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: >-
                'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
              method.response.header.Access-Control-Allow-Methods: '''GET,POST,OPTIONS'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json:
            'Fn::Join':
              - ''
              - - |
                  {
                - '  "body" : $input.json(''$''),'
                - '  "query": {'
                - |2
                      #foreach($param in $input.params().querystring.keySet())
                - '      "$param": '
                - '          "$util.escapeJavaScript($input.params().querystring.get($param))",'
                - |2
                          #end
                - '"customerIp": "$context.identity.sourceIp"'
                - " \t}\n"
                - |2
                   }
        Type: AWS
        Uri:
          'Fn::Sub': >-
            arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:<account-id>:function:UseMeForIntegrationTesting/invocations
        MethodResource:
          - StatusCode: '200'
            ResponseModels:
              application/json: Empty
    Metadata:
      'AWS::CloudFormation::Designer':
        id: adadf84e-97e6-4b94-bc35-4bd44caff7a4
  Deployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - HotelsResource
      - SearchResource
    Properties:
      RestApiId:
        Ref: RestApi
      StageName: release
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9c7b22b4-91ac-4261-b6be-bddda52ba066
  PropertiesElasticSearch:
    Type: 'AWS::Elasticsearch::Domain'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: acf6fbff-0275-4b14-8090-831069a218b8
Metadata:
  'AWS::CloudFormation::Designer':
    adadf84e-97e6-4b94-bc35-4bd44caff7a4:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 90
      z: 1
      embeds: []
    f88db4e6-a9ed-410a-a368-bb5cc7e2c221:
      size:
        width: 420
        height: 330
      position:
        x: 60
        'y': 90
      z: 1
      embeds:
        - 91b26e8c-4a3c-441a-b1f3-d1a737d5e6c0
        - 9c7b22b4-91ac-4261-b6be-bddda52ba066
    225600dc-f156-4ea2-bf90-7c6e997947fe:
      size:
        width: 150
        height: 150
      position:
        x: 60
        'y': 480
      z: 1
      embeds: []
      iscontainedinside:
        - f88db4e6-a9ed-410a-a368-bb5cc7e2c221
    91b26e8c-4a3c-441a-b1f3-d1a737d5e6c0:
      size:
        width: 150
        height: 150
      position:
        x: 90
        'y': 150
      z: 2
      parent: f88db4e6-a9ed-410a-a368-bb5cc7e2c221
      embeds: []
      iscontainedinside:
        - f88db4e6-a9ed-410a-a368-bb5cc7e2c221
    9c7b22b4-91ac-4261-b6be-bddda52ba066:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 150
      z: 2
      parent: f88db4e6-a9ed-410a-a368-bb5cc7e2c221
      embeds: []
      iscontainedinside:
        - f88db4e6-a9ed-410a-a368-bb5cc7e2c221
      dependson:
        - 91b26e8c-4a3c-441a-b1f3-d1a737d5e6c0
        - 225600dc-f156-4ea2-bf90-7c6e997947fe
    a36f685d-0d1e-4ab5-8bed-f725454c9994:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 210
      z: 1
      embeds: []
    437d7b08-2522-4767-93fb-a6d6c2cdd8b0:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 330
      z: 1
      embeds: []
    26cc3bf9-16b5-46fa-b773-679719a4f19a:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 450
      z: 1
      embeds: []
    b27df1b4-5407-4098-a832-facfecb264b8:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 480
      z: 1
      embeds: []
      dependson:
        - 26cc3bf9-16b5-46fa-b773-679719a4f19a
    27defe61-6107-4d89-91ac-c2cde38996b2:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 480
      z: 1
      embeds: []
      dependson:
        - 26cc3bf9-16b5-46fa-b773-679719a4f19a
    2c7c971a-30fc-4e90-876e-a938379acedd:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 570
      z: 1
      embeds: []
      dependson:
        - 26cc3bf9-16b5-46fa-b773-679719a4f19a
    acf6fbff-0275-4b14-8090-831069a218b8:
      size:
        width: 60
        height: 60
      position:
        x: 309.03813884744676
        'y': 549.1157772431792
      z: 0

